'use client';
import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'var(--bg-main)',
      color: 'var(--text-primary)',
      padding: '40px 24px'
    }}>
      <div style={{
        width: '100%',
        maxWidth: '650px',
        background: 'var(--bg-panel)',
        border: '1px solid var(--border-subtle)',
        borderRadius: '16px',
        padding: '40px',
        boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
        display: 'flex',
        flexDirection: 'column',
        gap: '24px'
      }}>
        <div style={{ borderBottom: '1px solid var(--border-subtle)', paddingBottom: '16px' }}>
          <h1 className="mono" style={{ fontSize: '20px', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '8px', letterSpacing: '0.05em' }}>
            PRIVACY POLICY
          </h1>
          <p className="mono text-muted" style={{ fontSize: '11px' }}>
            VC SCOPE OS // DATA COLLECTION & PROCESSING DISCLOSURE
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', fontSize: '13px', lineHeight: '1.6', color: 'var(--text-secondary)' }}>
          <section>
            <h3 className="mono" style={{ color: 'var(--text-primary)', fontSize: '12px', marginBottom: '8px', letterSpacing: '0.02em' }}>
              1. DATA WE COLLECT
            </h3>
            <p>
              VC Scope OS acts as an intelligence terminal for Venture Capital. To deliver core functionalities, we collect and store:
            </p>
            <ul style={{ paddingLeft: '20px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li><strong>Account Credentials:</strong> Hashed emails, full names, and securely salted/hashed passwords.</li>
              <li><strong>Portfolio & CRM Records:</strong> Deal pipeline metrics, startup profiles, founders' contact info, and deal notes.</li>
              <li><strong>Uploaded Materials:</strong> Pitch decks, financial models, and documentation uploaded for parsing.</li>
              <li><strong>Meeting Records:</strong> Call transcripts and summaries generated by the Live Meeting Copilot.</li>
            </ul>
          </section>

          <section>
            <h3 className="mono" style={{ color: 'var(--text-primary)', fontSize: '12px', marginBottom: '8px', letterSpacing: '0.02em' }}>
              2. HOW WE USE AND PROCESS DATA
            </h3>
            <p>
              Your data is used solely to generate AI deal-flow scoring, synthesize investment memos, map relationship graphs, and manage outreach campaigns. 
            </p>
            <p style={{ marginTop: '8px' }}>
              <strong>AI API Processing:</strong> Documents (e.g. pitch decks) and transcripts are analyzed using Google Gemini and Groq API endpoints. Data transmitted to these services is governed by their secure API privacy agreements and is <strong>not</strong> used to train public foundation models.
            </p>
          </section>

          <section>
            <h3 className="mono" style={{ color: 'var(--text-primary)', fontSize: '12px', marginBottom: '8px', letterSpacing: '0.02em' }}>
              3. STORAGE AND RETENTION
            </h3>
            <p>
              All database records (SQLite) are stored locally in the environment running the VC Scope OS backend. Pitch decks and metadata are hosted on secure local directories or private block storage. We retain this data as long as your workspace account exists.
            </p>
          </section>

          <section>
            <h3 className="mono" style={{ color: 'var(--text-primary)', fontSize: '12px', marginBottom: '8px', letterSpacing: '0.02em' }}>
              4. DATA CONTROL AND DELETION
            </h3>
            <p>
              As an authorized personnel, you hold full control over the data uploaded. You can update or permanently delete startup entries, uploaded decks, and user profiles directly through the interface or backend database cleanups.
            </p>
          </section>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border-subtle)', paddingTop: '24px', marginTop: '12px' }}>
          <span className="mono text-muted" style={{ fontSize: '11px' }}>Version 1.0.0 // Active</span>
          <Link href="/login" className="mono" style={{ fontSize: '12px', color: 'var(--accent-blue)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '6px' }}>
            ← Back to Login
          </Link>
        </div>
      </div>
    </div>
  );
}
